# Generated by Django 3.2 on 2023-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_iva',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MT', 'Monotributo')], default='CF', max_length=2, verbose_name='Tipo de IVA'),
        ),
    ]
