# Generated by Django 3.2 on 2023-11-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_auto_20231107_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_doc',
            name='diminutivo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_doc',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
